### ISSUE TITLE
more .vue file ?

### ISSUE THREAD

**Issue by krungle-mataman** [harmyderoman/simple-vue-grid#2]
Hello,

i did not understand how to work with the simple-vue-grid when i have more than one .vue File. Do i have to dublicate everything from my main.js into the other pages ?
i did design a global grid (row1-header/row2-content/row3-footer) and then the just add special aspects (for example about-page) in a cell (row/colums) which is a "part" of the global grid. so i want to overtake header and footer (this works) but it always put the about-content in the header-row instead of the content-row?
How can i managed that ? 

i defined a new grid-item in the right row (2) but this is placed always in row 1?

    <simple-grid-item
      tag="content" class="content"
      startColumn="1" columnSpan="1"
      startRow="2" row-span="1"
      lg-col="1" md-col="1" sm-col="1" xs-col="1"
    >

**Comment by krungle-mataman** [comment]
sorry- of course i defined it in the app.vue

**Comment by harmyderoman** [comment]
No need to duplicate anything.  After installation, all components from library are available globally in your project, that is, no import is needed either, in all .vue files.  
About the second question. I cannot imagine what is happening.  Can you show me all the code?
